<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>


  <ItemGroup>
    <!-- The popular COIExtended mod uses Lib.Harmony. Since Lib.Harmony and HarmonyX cannot be loaded side by side, we also use Lib.Harmony. -->
    <PackageVersion Include="Lib.Harmony" Version="2.4.1" />
  </ItemGroup>

</Project>
